---
# The following resources where utilised to create the config file and naming schemes:
# 

Core:
  Simulation-Mode: outoforder
  Clock-Frequency: 3.2
  Fetch-Block-Size: 32
  Vector-Length: 128
Process-Image:
  Heap-Size: 1073741824
  Stack-Size: 1048576
Register-Set:
  GeneralPurpose-Count: 380
  FloatingPoint/SVE-Count: 432
  Conditional-Count: 128
Pipeline-Widths:
  Commit: 8
  Dispatch-Rate: 2
  FrontEnd: 8
  LSQ-Completion: 3
Queue-Sizes:
  ROB: 630
  Load: 130
  Store: 60
Branch-Predictor:
  BTB-bitlength: 10
L1-Cache:
  Access-Latency: 3
  Store-Bandwidth: 32
  Load-Bandwidth: 48
  Permitted-Requests-Per-Cycle: 4
  Permitted-Loads-Per-Cycle: 3
  Permitted-Stores-Per-Cycle: 2
Ports:
  0:
    Portname: BR1
    Instruction-Support:
    - BRANCH
  1:
    Portname: BR2
    Instruction-Support:
    - BRANCH
  2:
    Portname: ALU1
    Instruction-Support:
    - INT_SIMPLE
  3:
    Portname: ALU2
    Instruction-Support:
    - INT_SIMPLE
  4:
    Portname: ALU3
    Instruction-Support:
    - INT_SIMPLE
  5:
    Portname: ALU4
    Instruction-Support:
    - INT_SIMPLE_ARTH
    - INT_SIMPLE_LOGICAL
  6:
    Portname: ALU5
    Instruction-Support:
    - INT_SIMPLE_ARTH
    - INT_SIMPLE_LOGICAL
    - INT_MUL
    - INT_DIV_OR_SQRT
  7:
    Portname: ALU6
    Instruction-Support:
    - INT_SIMPLE_ARTH
    - INT_SIMPLE_LOGICAL
    - INT_MUL
  8:
    Portname: ST
    Instruction-Support:
    - STORE
  9:
    Portname: ST_LD
    Instruction-Support:
    - LOAD
    - STORE
  10:
    Portname: LD1
    Instruction-Support:
    - LOAD
  11:
    Portname: LD2
    Instruction-Support:
    - LOAD
  12:
    Portname: FP_SIMD1
    Instruction-Support:
    - FP_SIMPLE
    - FP_MUL
  13:
    Portname: FP_SIMD2
    Instruction-Support:
    - FP_SIMPLE
    - FP_MUL
  14:
    Portname: FP_SIMD3
    Instruction-Support:
    - FP_SIMPLE
    - FP_MUL
  15:
    Portname: FP_AND_FDIV
    Instruction-Support:
    - FP
Reservation-Stations:
  0:
    Size: 24
    Ports:
    - BR1
  1:
    Size: 24
    Ports:
    - BR2
  2:
    Size: 24
    Ports:
    - ALU1
  3:
    Size: 26
    Ports:
    - ALU2
  4:
    Size: 16
    Ports:
    - ALU3
  5:
    Size: 12
    Ports:
    - ALU4
  6:
    Size: 28
    Ports:
    - ALU5
  7:
    Size: 28
    Ports:
    - ALU6
  8:
    Size: 48
    Ports:
    - ST
    - ST_LD
    - LD1
    - LD2
  9:
    Size: 36
    Ports:
    - FP_SIMD1
  10:
    Size: 36
    Ports:
    - FP_SIMD2
  11:
    Size: 36
    Ports:
    - FP_SIMD3
  12:
    Size: 36
    Ports:
    - FP_AND_FDIV
Execution-Units:
  0:
    Pipelined: True
    Blocking-Groups:
  1:
    Pipelined: True
    Blocking-Groups: 
  2:
    Pipelined: True
    Blocking-Groups: 
    - INT_SIMPLE_CVT
  3:
    Pipelined: True
    Blocking-Groups: 
    - INT_SIMPLE_CVT
  4:
    Pipelined: True
    Blocking-Groups: 
    - INT_SIMPLE_CVT
  5:
    Pipelined: True
    Blocking-Groups: 
  6:
    Pipelined: True
    Blocking-Groups: 
  7:
    Pipelined: True
    Blocking-Groups: 
  8:
    Pipelined: True
    Blocking-Groups: 
  9:
    Pipelined: True
    Blocking-Groups: 
  10:
    Pipelined: True
    Blocking-Groups: 
  11:
    Pipelined: True
    Blocking-Groups: 
  12:
    Pipelined: True
    Blocking-Groups: 
  13:
    Pipelined: True
    Blocking-Groups: 
  14:
    Pipelined: True
    Blocking-Groups: 
  15:
    Pipelined: True
    Blocking-Groups: 
Latencies:
  0:
    Instruction-Groups: 
    - INT
    Execution-Latency: 2
    Execution-Throughput: 2
  1:
    Instruction-Groups: 
    - INT_SIMPLE_ARTH_NOSHIFT
    - INT_SIMPLE_LOGICAL_NOSHIFT
    - INT_SIMPLE_CMP
    Execution-Latency: 1
    Execution-Throughput: 1
  2:
    Instruction-Groups: 
    - INT_MUL
    Execution-Latency: 3
    Execution-Throughput: 1
  3:
    Instruction-Groups: 
    - INT_DIV_OR_SQRT
    Execution-Latency: 8
    Execution-Throughput: 2
  4:
    Instruction-Groups: 
    - FP
    Execution-Latency: 2
    Execution-Throughput: 1
  5:
    Instruction-Groups: 
    - FP_SIMPLE_ARTH
    - FP_SIMPLE_CVT
    Execution-Latency: 3
    Execution-Throughput: 1
  6:
    Instruction-Groups: 
    - FP_DIV_OR_SQRT
    Execution-Latency: 9
    Execution-Throughput: 2
  7:
    Instruction-Groups: 
    - FP_MUL
    Execution-Latency: 4
    Execution-Throughput: 1
  8:
    Instruction-Groups: 
    - LOAD_SCALAR
    - LOAD_VECTOR
    - STORE_SCALAR
    - STORE_VECTOR
    Execution-Latency: 10
    Execution-Throughput: 1
# CPU-Info mainly used to generate a replica of the special (or system) file directory 
# structure
CPU-Info:
  # Set Generate-Special-Dir to 'T' to generate the special files directory, or to 'F' to not.
  # (Not generating the special files directory may require the user to copy over files manually)
  Generate-Special-Dir: T
  # Core-Count MUST be 1 as multi-core is not supported at this time. (A64FX true value is 48)
  Core-Count: 1
  # Socket-Count MUST be 1 as multi-socket simulations are not supported at this time. (A64FX true value is 1)
  Socket-Count: 1
  # SMT MUST be 1 as Simultanious-Multi-Threading is not supported at this time. (A64FX true value is 1)
  SMT: 1
  # Below are the values needed to generate /proc/cpuinfo
  BogoMIPS: 200.00
  Features: fp asimd evtstrm sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm fcma dcpop sve
  CPU-Implementer: "0x46"
  CPU-Architecture: 8
  CPU-Variant: "0x1"
  CPU-Part: "0x001"
  CPU-Revision: 0
  # Package-Count is used to generate 
  # /sys/devices/system/cpu/cpu{0..Core-Count}/topology/{physical_package_id, core_id}
  Package-Count: 1
